### ISSUE TITLE
Application generation does not work at all with latest v2.0.0-beta.1 version

### ISSUE THREAD

**Issue by dmadunic** [jhipster/generator-jhipster-quarkus#235]
**Describe the bug**
jhipster generator fails to generate application when invoked with latest v2.0.0-beta.1 version of quarkus plugin.

**To Reproduce**

1.  Checkout jhipster/generator-jhipster-quarkus
2.  Link generator
3.  Create new folder, and link generator inside of it: npm link generator-jhipster-quarkus
4.  Run: jhipster --blueprint quarkus

**Expected behavior**
Skeleton of the new application to be generated

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser [e.g. chrome, safari]
-   Version v2.0.0-beta.1
- Jhipster version installed globally 7.1.0

**Error**
```
Welcome to JHipster Quarkus v2.0.0-beta.1
Application files will be generated in folder: /home/domagoj/git/geodata/geodata-rest-quarkus
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://github.com/jhipster/jhipster-quarkus
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

 ______________________________________________________________________________

  JHipster update available: 7.5.0 (current: 6.10.5)

  Run npm install -g generator-jhipster to update.

 ______________________________________________________________________________

? What is the base name of your application? geodataRestQuarkus
ERROR! jhContext.setupServerOptions is not a function
TypeError: jhContext.setupServerOptions is not a function
    at new module.exports (/home/domagoj/.nvm/versions/node/v16.13.0/lib/node_modules/generator-jhipster-quarkus/generators/server/index.js:22:19)
    at Environment.instantiate (/home/domagoj/.nvm/versions/node/v16.13.0/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:794:23)
    at instantiate (/home/domagoj/.nvm/versions/node/v16.13.0/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:1196:23)
    at module.exports.composeWith (/home/domagoj/.nvm/versions/node/v16.13.0/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:1227:33)
    at module.exports.composeServer (/home/domagoj/.nvm/versions/node/v16.13.0/lib/node_modules/generator-jhipster-quarkus/generators/app/index.js:106:22)
    at Object.<anonymous> (/home/domagoj/.nvm/versions/node/v16.13.0/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:976:25)
    at /home/domagoj/.nvm/versions/node/v16.13.0/lib/node_modules/generator-jhipster-quarkus/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /home/domagoj/.nvm/versions/node/v16.13.0/lib/node_modules/generator-jhipster-quarkus/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/home/domagoj/.nvm/versions/node/v16.13.0/lib/node_modules/generator-jhipster-quarkus/node_modules/yeoman-generator/lib/index.js:977:11)
Unhandled promise rejection at:
TypeError: jhContext.setupServerOptions is not a function
```

**Comment by dmadunic** [comment]
It does work with jhipster version 6.10.5 though ...
